<a href="https://colab.research.google.com/github/shriniiketan/ML_project_SVM/blob/main/rbf_5/10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [82]:
import pandas as pd
import tensorflow as tf
from keras.layers import BatchNormalization
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [83]:
X_train = pd.read_csv('x_train_5.csv')

print(X_train.shape[:1])

(56,)


In [84]:
Y_train = pd.read_csv('y_train_5.csv')

print(Y_train.values.ravel().shape)

(56,)


In [85]:
X_test = pd.read_csv('x_test.csv')

print(X_test.shape)

(568, 30)


In [86]:
Y_test = pd.read_csv('y_test.csv')

print(Y_test.shape)

(568, 1)


In [87]:
X_train = X_train.values
X_test = X_test.values

In [88]:
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
Y_train = scaler.fit_transform(Y_train)
Y_test = scaler.fit_transform(Y_test)
X_test = scaler.fit_transform(X_test)
print(X_test.shape)
print(X_test)

(568, 30)
[[0.64314449 0.27257355 0.61578329 ... 0.63917526 0.23358959 0.22287813]
 [0.60149557 0.3902604  0.59574321 ... 0.83505155 0.40370589 0.21343303]
 [0.2100904  0.36083869 0.23350149 ... 0.88487973 1.         0.77371114]
 ...
 [0.45525108 0.62123774 0.44578813 ... 0.48728522 0.12872068 0.1519087 ]
 [0.64456434 0.66351031 0.66553797 ... 0.91065292 0.49714173 0.45231536]
 [0.03686876 0.50152181 0.02853984 ... 0.         0.25744136 0.10068215]]


In [89]:
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report 

svc_model = SVC()
svc_model.fit(X_train,Y_train)



/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [90]:
Y_predict = svc_model.predict(X_test)
print(classification_report(Y_test, Y_predict))





              precision    recall  f1-score   support

         0.0       0.85      1.00      0.92       357
         1.0       1.00      0.70      0.82       211

    accuracy                           0.89       568
   macro avg       0.93      0.85      0.87       568
weighted avg       0.91      0.89      0.88       568



In [91]:
param_grid = {'C': [1 , 10, 100, 1000, 10000, 100000, 1000000, 10000000, 10000000, 100000000], 'gamma': [0.1, 0.01, 0.0001, 0.00001, 0.000001,0.0000001], 'kernel': ['rbf']}
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=2)
grid.fit(X_train,Y_train)


Fitting 5 folds for each of 60 candidates, totalling 300 fits
[CV] END .........................C=1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END .........................C=1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END .........................C=1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END .........................C=1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END .........................C=1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END ........................C=1, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ........................C=1, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ........................C=1, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ........................C=1, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ........................C=1, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ......................C=1, gamma=0.0001, kernel=rbf; total time=   0.0s
[CV] END ......................C=1, gamma=0.000

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for exam

[CV] END ......................C=10, gamma=1e-06, kernel=rbf; total time=   0.0s
[CV] END ......................C=10, gamma=1e-07, kernel=rbf; total time=   0.0s
[CV] END ......................C=10, gamma=1e-07, kernel=rbf; total time=   0.0s
[CV] END ......................C=10, gamma=1e-07, kernel=rbf; total time=   0.0s
[CV] END ......................C=10, gamma=1e-07, kernel=rbf; total time=   0.0s
[CV] END ......................C=10, gamma=1e-07, kernel=rbf; total time=   0.0s
[CV] END .......................C=100, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END .......................C=100, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END .......................C=100, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END .......................C=100, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END .......................C=100, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END ......................C=100, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ...................

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for exam

[CV] END ....................C=1000, gamma=1e-05, kernel=rbf; total time=   0.0s
[CV] END ....................C=1000, gamma=1e-05, kernel=rbf; total time=   0.0s
[CV] END ....................C=1000, gamma=1e-06, kernel=rbf; total time=   0.0s
[CV] END ....................C=1000, gamma=1e-06, kernel=rbf; total time=   0.0s
[CV] END ....................C=1000, gamma=1e-06, kernel=rbf; total time=   0.0s
[CV] END ....................C=1000, gamma=1e-06, kernel=rbf; total time=   0.0s
[CV] END ....................C=1000, gamma=1e-06, kernel=rbf; total time=   0.0s
[CV] END ....................C=1000, gamma=1e-07, kernel=rbf; total time=   0.0s
[CV] END ....................C=1000, gamma=1e-07, kernel=rbf; total time=   0.0s
[CV] END ....................C=1000, gamma=1e-07, kernel=rbf; total time=   0.0s
[CV] END ....................C=1000, gamma=1e-07, kernel=rbf; total time=   0.0s
[CV] END ....................C=1000, gamma=1e-07, kernel=rbf; total time=   0.0s
[CV] END ...................

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for exam

[CV] END .................C=100000, gamma=0.0001, kernel=rbf; total time=   0.0s
[CV] END .................C=100000, gamma=0.0001, kernel=rbf; total time=   0.0s
[CV] END .................C=100000, gamma=0.0001, kernel=rbf; total time=   0.0s
[CV] END .................C=100000, gamma=0.0001, kernel=rbf; total time=   0.0s
[CV] END ..................C=100000, gamma=1e-05, kernel=rbf; total time=   0.0s
[CV] END ..................C=100000, gamma=1e-05, kernel=rbf; total time=   0.0s
[CV] END ..................C=100000, gamma=1e-05, kernel=rbf; total time=   0.0s
[CV] END ..................C=100000, gamma=1e-05, kernel=rbf; total time=   0.0s
[CV] END ..................C=100000, gamma=1e-05, kernel=rbf; total time=   0.0s
[CV] END ..................C=100000, gamma=1e-06, kernel=rbf; total time=   0.0s
[CV] END ..................C=100000, gamma=1e-06, kernel=rbf; total time=   0.0s
[CV] END ..................C=100000, gamma=1e-06, kernel=rbf; total time=   0.0s
[CV] END ..................C

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for exam

[CV] END .................C=10000000, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END .................C=10000000, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END .................C=10000000, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END .................C=10000000, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END .................C=10000000, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ...............C=10000000, gamma=0.0001, kernel=rbf; total time=   0.0s
[CV] END ...............C=10000000, gamma=0.0001, kernel=rbf; total time=   0.0s
[CV] END ...............C=10000000, gamma=0.0001, kernel=rbf; total time=   0.0s
[CV] END ...............C=10000000, gamma=0.0001, kernel=rbf; total time=   0.0s
[CV] END ...............C=10000000, gamma=0.0001, kernel=rbf; total time=   0.0s
[CV] END ................C=10000000, gamma=1e-05, kernel=rbf; total time=   0.0s
[CV] END ................C=10000000, gamma=1e-05, kernel=rbf; total time=   0.0s
[CV] END ................C=1

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for exam

[CV] END ................C=10000000, gamma=1e-05, kernel=rbf; total time=   0.0s
[CV] END ................C=10000000, gamma=1e-06, kernel=rbf; total time=   0.0s
[CV] END ................C=10000000, gamma=1e-06, kernel=rbf; total time=   0.0s
[CV] END ................C=10000000, gamma=1e-06, kernel=rbf; total time=   0.0s
[CV] END ................C=10000000, gamma=1e-06, kernel=rbf; total time=   0.0s
[CV] END ................C=10000000, gamma=1e-06, kernel=rbf; total time=   0.0s
[CV] END ................C=10000000, gamma=1e-07, kernel=rbf; total time=   0.0s
[CV] END ................C=10000000, gamma=1e-07, kernel=rbf; total time=   0.0s
[CV] END ................C=10000000, gamma=1e-07, kernel=rbf; total time=   0.0s
[CV] END ................C=10000000, gamma=1e-07, kernel=rbf; total time=   0.0s
[CV] END ................C=10000000, gamma=1e-07, kernel=rbf; total time=   0.0s
[CV] END .................C=100000000, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END .................C=

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for exam

GridSearchCV(estimator=SVC(),
             param_grid={'C': [1, 10, 100, 1000, 10000, 100000, 1000000,
                               10000000, 10000000, 100000000],
                         'gamma': [0.1, 0.01, 0.0001, 1e-05, 1e-06, 1e-07],
                         'kernel': ['rbf']},
             verbose=2)

In [92]:
print(grid.best_params_)
  
print(grid.best_estimator_)

{'C': 100, 'gamma': 0.01, 'kernel': 'rbf'}
SVC(C=100, gamma=0.01)


In [93]:
grid_predictions = grid.predict(X_test)
print(classification_report(Y_test,grid_predictions))

              precision    recall  f1-score   support

         0.0       0.88      1.00      0.94       357
         1.0       1.00      0.77      0.87       211

    accuracy                           0.92       568
   macro avg       0.94      0.89      0.90       568
weighted avg       0.93      0.92      0.91       568

